### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by Greenjam94** [Greenjam94/railsWithUser#1]
@chrisvfritz, Please help. I've spent too long trying to read through how to set up Travis CI correctly, the builds keep failing and I don't know what else to try. Can you please check my .travis.yml and tell me if you notice anything wrong?

I'm going to check your cheatsheet repo for any other hints and then I'm giving up on this. The site should still work fine on Heroku, I pushed it manually...

**Comment by chrisvfritz** [comment]
No problem! I *think* changing your `.travis.yml` file to the following should fix the problem:

``` yaml
language: ruby
rvm:
  - 2.0.0

bundler_args: --without development production # to prevent us from unnecessarily installing gems

# just some database setup
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

script: echo Build complete # we're doing this to prevent travis ci from trying to run any tests, since we don't have any

deploy:
  provider: heroku
  api_key:
    secure: # to encrypt your API key, so that no one else can see it, run the following in your terminal, then paste the result here: travis encrypt $(heroku auth:token)
  app: # this should be the name of your Heroku app (the herokuapp.com subdomain)
  on:
    repo: Greenjam94/railsWithUser
  run: "bundle exec rake db:migrate" # migrates the database on heroku after deploy
```

This assumes that you have a `config/database.yml.travis` file, so create one with these contents:

``` yaml
test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
```

I hope that helps! If it still doesn't work, just add me as a contributor to this repo and I'll be happy to help troubleshoot further.
